### PR TITLE
Adding health exchange to the configurable menu apps

### PR DESCRIPTION
**Pull request by Daphne210**

### CODE REVIEW

**Review by jabahum — APPROVED** [review]
Thanks @Daphne210 LGTM

**Comment by jabahum** [comment]
resolve these conflicts as well

**Comment by Daphne210** [comment]
> resolve these conflicts as well

@jabahum This has been fixed

**Comment by jabahum** [comment]
@Daphne210 it has some build errors

**Review by akileng56 — APPROVED** [review]

**Review by jabahum — APPROVED** [review]
Thanks

**Pull request merged**
